CREATE DATABASE CrudADO;
GO

USE CrudADO;
GO

CREATE TABLE Persons(
	Id INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	Gender SMALLINT NOT NULL,
	Ethnicity SMALLINT NOT NULL,
	BirthDate DATE NOT NULL,
);